name: Rust

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rust: [nightly, stable, 1.41.1]
        include:
          - rust: 1.41.1
            extra-test-opts: -- --skip ui
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        default: true
    - run: cargo build
    - name: Prepare UI tests for nightly
      if: matrix.rust == 'nightly'
      run: for x in test_suite/ui/*.nightly; do cp "$x" "${x%.nightly}"; done
    - run: cargo test --all ${{ matrix.extra-test-opts }}
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: clippy
    - run: cargo clippy -- -D warnings
