name: Rust

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rust: [nightly, stable, 1.34.2]
        include:
          - rust: 1.34.2
            extra-test-opts: -- --skip ui
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        default: true
    - run: cargo build
    - run: cargo test --all ${{ matrix.extra-test-opts }}
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: clippy
    - run: cargo clippy -- -D warnings
